site_name: Akapy Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guides: how-to-guides.md
  - References:
    - Auth: references/auth.md
