name: Pull Request Workflow
on:
  pull_request:
    - opened
    - edited
    - synchronize
permissions:
  pull-requests: read
jobs:
  lint-title:
    name: Validate PR Title
    secrets: inherit
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        with:
          types: |
            fix
            feat
            refactor
            revert
            chore
          requireScope: false

  dry-run:
    name: Dry-Run Pypi
    uses: ./.github/workflows/python-publish.yml
    secrets: inherit
    with:
      DRY_RUN: true
      PUBLISH: false
