name: Publish to pypi
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    uses: ./.github/workflows/python-publish.yml
    secrets: inherit
    with:
      DRY_RUN: false
      PUBLISH: true
