name: Upload Python Package
on:
  workflow_call:
    inputs:
      DRY_RUN:
        description: Bool to check for dry-run
        type: boolean
        default: true
      PUBLISH:
        description: Bool if to publish to PyPi Prod
        type: boolean
        default: false
  workflow_dispatch:
permissions:
  contents: read
jobs:
  dry-run:
    if: ${{ inputs.DRY_RUN }}
    name: PyPi Dry-Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and dry-run publish to PyPi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
          poetry_install_options: "--sync"
          poetry_publish_options: "--dry-run"
  
  publish:
    if: ${{ inputs.PUBLISH }}
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
          poetry_install_options: "--sync"
